name: Run tests
on: [push] 
permissions:
  id-token: write
  contents: write

# on: [push]
#   # workflow_dispatch:
#   #   inputs:
#   #     ALLURE_JOB_RUN_ID:
#   #       description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
#   #     ALLURE_USERNAME:
#   #       description: ALLURE_USERNAME service parameter. Leave blank.

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: https://praveen.testops.cloud/
  ALLURE_PROJECT_ID: 1
  ALLURE_RESULTS: allure-results

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Login to Azure Public Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
                  
      - name: Get resource group with Azure CLI
        run: az group list

      - name: Install vsts
        run: npm install -g vsts-npm-auth

      - name: Use .npmrc   
        uses: bduff9/use-npmrc@v1.2
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}    

      - name: Install npm packages
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Azure PSDT Feed         
        run: |
          echo "Y" | npm init -y @azure/microsoft-playwright-testing-private-preview

      - name: Run Playwright tests        
        run: allurectl watch -- npx playwright test -c playwright.service.config.ts --reporter=allure-playwright
        env:
            PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}         

    
